version: '3.8'
services:
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 8003"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8003:8003"
    expose:
      - "8003"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    env_file:
      - .env
